apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kserve
resources:
  - servingruntime-vllm.yaml
  - servingruntime-triton.yaml
  - inferenceservice-vllm-sample.yaml
  - inferenceservice-triton-sample.yaml

