apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  name: triton-runtime
  namespace: kserve
spec:
  supportedModelFormats:
    - name: tensorflow
      version: "2"
    - name: pytorch
      version: "1"
    - name: onnx
      version: "1"
  containers:
    - name: kserve-container
      image: nvcr.io/nvidia/tritonserver:24.01-py3
      args: ["tritonserver", "--model-repository=/mnt/models"]
      ports:
        - containerPort: 8000
        - containerPort: 8001
        - containerPort: 8002
      resources:
        limits:
          nvidia.com/gpu: 1
