apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kserve
resources:
  - ../../upstream # vendor KServe manifests here (install/base)
patches:
  - path: patches/kserve-configmap.yaml
  - path: patches/modelmesh-enable.yaml

