apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: pod-disruption-budgets
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - cluster: dev-mlops-cluster-01
        url: https://kubernetes.default.svc
  template:
    metadata:
      name: '{{cluster}}-pdbs'
    spec:
      project: default
      source:
        repoURL: https://github.com/your-org/argoeks.git
        targetRevision: HEAD
        path: kubernetes/platform/pdbs
      destination:
        server: '{{url}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
