apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: external-secrets-fleet
  namespace: argocd
spec:
  generators:
    - clusters: {}
  template:
    metadata:
      name: "{{name}}-external-secrets"
    spec:
      project: default
      source:
        repoURL: https://charts.external-secrets.io
        chart: external-secrets
        targetRevision: 0.9.16
        helm:
          releaseName: external-secrets
          parameters:
          - name: installCRDs
            value: "true"
          - name: serviceAccount.create
            value: "true"
          - name: serviceAccount.name
            value: "external-secrets"
          - name: serviceAccount.annotations.eks\.amazonaws\.com/role-arn
            value: "arn:aws:iam::555989351930:role/external-secrets-dev-mlops-cluster-01"
      destination:
        server: "{{server}}"
        namespace: external-secrets
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true

