apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform controllers and shared services
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: '*'
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  roles:
    - name: admin
      description: Full access to project
      policies:
        - p, proj:platform:admin, applications, *, platform/*, allow
      groups:
        - platform:admin
    - name: readonly
      description: Read-only access to project
      policies:
        - p, proj:platform:readonly, applications, get, platform/*, allow
      groups:
        - platform:readonly

